version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      DB_NAMR: currency_db
      DB_USERNAME: postgres
      DB_PASSWORD: 2006
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
